In [3]:
import numpy as np

# a. Basic ndarray
basic_array = np.array([1, 2, 3, 4, 5])
print("Basic ndarray:")
print(basic_array)

# b. Array of zeros
zeros_array = np.zeros((3, 3))
print("\nArray of zeros:")
print(zeros_array)

# c. Array of ones
ones_array = np.ones((2, 5))
print("\nArray of ones:")
print(ones_array)

# d. Random numbers in ndarray
random_array = np.random.rand(3, 3)
print("\nRandom numbers ndarray:")
print(random_array)

# e. An array of your choice
custom_array = np.array([[10, 20], [30, 40]])
print("\nCustom array:")
print(custom_array)

# f. Identity matrix in NumPy
identity_matrix = np.eye(4)
print("\nIdentity matrix:")
print(identity_matrix)

# g. Evenly spaced ndarray
spaced_array = np.linspace(0, 10, 6)
print("\nEvenly spaced ndarray:")
print(spaced_array)


Basic ndarray:
[1 2 3 4 5]

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array of ones:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Random numbers ndarray:
[[0.08716718 0.02055828 0.84450773]
 [0.19692567 0.09009406 0.07253878]
 [0.14989825 0.23488363 0.43024635]]

Custom array:
[[10 20]
 [30 40]]

Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Evenly spaced ndarray:
[ 0.  2.  4.  6.  8. 10.]


In [6]:
import numpy as np

# Creating an array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Array:")
print(arr)

# a. Dimensions of NumPy array
print("Dimensions (ndim):", arr.ndim)

# b. Shape of NumPy array
print("Shape:", arr.shape)

# c. Size of NumPy array
print("Size:", arr.size)

# d. Reshaping the NumPy array
reshaped_arr = arr.reshape(3, 2)
print("Reshaped Array (3x2):")
print(reshaped_arr)

# e. Flattening the arraylattened_arr = arr.flatten()
print("Flattened Array:")
print(flattened_arr)

# f. Transpose of NumPy array
transposed_arr = arr.T
print("Transposed Array:")
print(transposed_arr)


Original Array:
[[1 2 3]
 [4 5 6]]
Dimensions (ndim): 2
Shape: (2, 3)
Size: 6
Reshaped Array (3x2):
[[1 2]
 [3 4]
 [5 6]]
Flattened Array:


NameError: name 'flattened_arr' is not defined

In [2]:
import numpy as np

# Creating an array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Array:")
print(arr)

# a. Dimensions of NumPy array
print("Dimensions (ndim):", arr.ndim)

# b. Shape of NumPy array
print("Shape:", arr.shape)

# c. Size of NumPy array
print("Size:", arr.size)

# d. Reshaping the NumPy array
reshaped_arr = arr.reshape(3, 2)
print("Reshaped Array (3x2):")
print(reshaped_arr)

# e. Flattening the array
flattened_arr = arr.flatten()
print("Flattened Array:")
print(flattened_arr)

# f. Transpose of NumPy array
transposed_arr = arr.T
print("Transposed Array:")
print(transposed_arr)


Original Array:
[[1 2 3]
 [4 5 6]]
Dimensions (ndim): 2
Shape: (2, 3)
Size: 6
Reshaped Array (3x2):
[[1 2]
 [3 4]
 [5 6]]
Flattened Array:
[1 2 3 4 5 6]
Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


In [54]:
import numpy as np

# 1-D Array Expanding and Squeezing
a = np.array([10, 20, 30, 40, 50, 60])
print("1-D Array:")
print(a)

# 2-D Array 
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("2-D Array:")
print(b)


# 3-D Array 
c = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("3-D Array:")
print(c)

# a. Expanding a NumPy array
a_expanded0 = np.expand_dims(a, axis=0)
print("Expanded Array a (axis=0):")
print(a_expanded0)

a_expanded1 = np.expand_dims(a, axis=1)
print("Expanded Array a (axis=1):")
print(a_expanded1)

b_expanded0 = np.expand_dims(b, axis=0)
print("Expanded Array b (axis=0):")
print(b_expanded0)

b_expanded1 = np.expand_dims(b, axis=1)
print("Expanded Array b (axis=1):")
print(b_expanded1)

c_expanded0 = np.expand_dims(c, axis=0)
print("Expanded Array c (axis=0):")
print(c_expanded0)

c_expanded1 = np.expand_dims(c, axis=1)
print("Expanded Array c (axis=1):")
print(c_expanded1)



# b. Squeezing a NumPy array
a_squeezed0 = np.squeeze(a_expanded0)
print("Squeezed Array a (axis=0):")
print(a_squeezed0)

a_squeezed1 = np.expand_dims(a_expanded1)
print("Squeezed Array a (axis=1):")
print(a_squeezed1)

b_expanded0 = np.expand_dims(b_expanded0)
print("Squeezed Array b (axis=0):")
print(b_expanded0)

b_expanded1 = np.expand_dims(b_expanded1)
print("Squeezed Array b (axis=1):")
print(b_expanded1)

c_expanded0 = np.expand_dims(c_expanded0)
print("Squeezed Array c (axis=0):")
print(c_expanded0)

c_expanded1 = np.expand_dims(c_expanded1)
print("Squeezed Array c (axis=1):")
print(c_expanded1)

# c. Sorting in NumPy arrays
sorted_arr = np.sort(a)
print("Sorted Array:")
print(sorted_arr)


1-D Array:
[10 20 30 40 50 60]
2-D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3-D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Expanded Array a (axis=0):
[[10 20 30 40 50 60]]
Expanded Array a (axis=1):
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]
Expanded Array b (axis=0):
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Expanded Array b (axis=1):
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
Expanded Array c (axis=0):
[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
Expanded Array c (axis=1):
[[[[1 2]
   [3 4]]]


 [[[5 6]
   [7 8]]]]
Sorted Array:
[10 20 30 40 50 60]


In [6]:
import numpy as np

# 1-D Array Slicing
a = np.array([10, 20, 30, 40, 50, 60])
print("1-D Array:")
print(a)

print("Slicing 1-D (1:4):", a[1:4])
print("Slicing with step (0:6:2):", a[0:6:2])
print("Negative slicing (-4:-1):", a[-4:-1])

# 2-D Array Slicing
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("2-D Array:")
print(b)

print("Row 0, Columns 0-2:", b[0, 0:2])
print("Rows 0-2, Column 1:", b[0:2, 1])
print("Submatrix (rows 0:2, cols 1:3):", b[0:2, 1:3])

# 3-D Array Slicing
c = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("3-D Array:")
print(c)

print("Accessing 3-D element [0,1,1]:", c[0, 1, 1])
print("Slice 3-D (0:1, :, :):", c[0:1, :, :])

# Negative slicing example
print("Negative Slicing 2-D (rows -2: , cols -3:):", b[-2:, -3:])


1-D Array:
[10 20 30 40 50 60]
Slicing 1-D (1:4): [20 30 40]
Slicing with step (0:6:2): [10 30 50]
Negative slicing (-4:-1): [30 40 50]
2-D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row 0, Columns 0-2: [1 2]
Rows 0-2, Column 1: [2 5]
Submatrix (rows 0:2, cols 1:3): [[2 3]
 [5 6]]
3-D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Accessing 3-D element [0,1,1]: 4
Slice 3-D (0:1, :, :): [[[1 2]
  [3 4]]]
Negative Slicing 2-D (rows -2: , cols -3:): [[4 5 6]
 [7 8 9]]


In [8]:
import numpy as np

# Sample arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

print("Array 1:", arr1)
print("Array 2:", arr2)

# a. Stacking ndarrays
print("Vertical Stack (vstack):", np.vstack((arr1, arr2)))
print("Horizontal Stack (hstack):", np.hstack((arr1, arr2)))

# b. Concatenating ndarrays
print("Concatenate axis=0:", np.concatenate((arr1, arr2), axis=0))
print("Concatenate axis=1:", np.concatenate((arr1, arr2), axis=1))

# c. Broadcasting in NumPy Arrays
arr3 = np.array([1, 2, 3])   # 1-D array
print("Array 3 (1-D):", arr3)

print("Broadcasting Example (arr1 + arr3):", arr1 + arr3)


Array 1: [[1 2 3]
 [4 5 6]]
Array 2: [[ 7  8  9]
 [10 11 12]]
Vertical Stack (vstack): [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontal Stack (hstack): [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Concatenate axis=0: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Concatenate axis=1: [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Array 3 (1-D): [1 2 3]
Broadcasting Example (arr1 + arr3): [[2 4 6]
 [5 7 9]]


In [45]:
import numpy as np

# Original array
arr = np.array([10, 30, 20, 50, 40])
print("Original Array:")


# 2-D Array Slicing
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# a. Expanding a NumPy array
a_expanded = np.expand_dims(b, axis=1)
print("Expanded Array (axis=1):")
print(a_expanded)

#b_expanded = np.expand_dims(arr, axis=1)
#print("Expanded Array (axis=1):")
#print(b_expanded)

# b. Squeezing a NumPy array
squeezed = np.squeeze(b)
print("Squeezed Array:")
print(squeezed)




Original Array:
Expanded Array (axis=1):
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
Squeezed Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
